# Generated by Django 4.1.4 on 2022-12-27 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MTG_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='commander',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commander_card', to='MTG_API.card'),
        ),
    ]
