# Generated by Django 4.1.4 on 2022-12-28 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MTG_API', '0003_alter_deck_commander'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_deck', to='MTG_API.card'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list_deck', to='MTG_API.list'),
        ),
        migrations.AlterField(
            model_name='deck',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_deck', to='MTG_API.user'),
        ),
    ]
