# Generated by Django 4.1.4 on 2022-12-28 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MTG_API', '0004_alter_deck_card_alter_deck_list_alter_deck_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='cards',
            field=models.ManyToManyField(related_name='list_card', through='MTG_API.Deck', to='MTG_API.card'),
        ),
    ]
