# Generated by Django 4.1.4 on 2022-12-29 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MTG_API', '0005_alter_list_cards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deck',
            name='card',
        ),
        migrations.AlterField(
            model_name='deck',
            name='commander',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commander_card', to='MTG_API.card'),
        ),
        migrations.AddField(
            model_name='deck',
            name='card',
            field=models.ManyToManyField(to='MTG_API.card'),
        ),
    ]
